// <auto-generated />
namespace scratch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_Name_To_MembershipType_And_In_Sql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Name_To_MembershipType_And_In_Sql));
        
        string IMigrationMetadata.Id
        {
            get { return "202103240929474_Added_Name_To_MembershipType_And_In_Sql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
